// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvukkqrjfrzvnytpcfjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2dWtrcXJqZnJ6dm55dHBjZmpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNTQxNDQsImV4cCI6MjA2NzgzMDE0NH0.9RO3Mgc4JHmgRn6WezftkvZlRzptkDuBrwdSmE1Hx_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});